services:
  api:
    volumes:
      - ./src/api:/app

  rag-core:
    volumes:
      - ./src/rag_core:/app

  llm-gateway:
    volumes:
      - ./src/llm_gateway:/app

  streamlit-ui:
    volumes:
      - ./src/streamlit_ui:/app