services:
  cli:
    volumes:
      - ./src/cli:/app

  rag-core:
    volumes:
      - ./src/rag-core:/app

  llm-gateway:
    volumes:
      - ./src/llm-gateway:/app

  streamlit-ui:
    volumes:
      - ./src/streamlit-ui:/app