apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag-app.fullname" . }}-rag-core
  labels:
    app.kubernetes.io/component: rag-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: rag-core
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rag-core
    spec:
      containers:
        - name: rag-core
          image: "{{ index .Values "rag-core" "image" "repository" }}:{{ index .Values "rag-core" "image" "tag" }}"
          imagePullPolicy: {{ index .Values "rag-core" "image" "pullPolicy" }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "rag-app.fullname" . }}-rag-core-config
            - secretRef:
                name: {{ include "rag-app.fullname" . }}-rag-core-secrets