apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rag-app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "rag-app.fullname" . }}-frontend-service
                port:
                  name: http
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "rag-app.fullname" . }}-rag-core-service 
                port:
                  name: http
          - path: /minio(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-minio 
                port:
                  name: http-console
