apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-app.fullname" . }}-llm-gateway-service
spec:
  type: {{ index .Values "llm-gateway" "service" "type" }}
  ports:
    - port: {{ index .Values "llm-gateway" "service" "port" }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: llm-gateway
