apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-app.fullname" . }}-rag-core-secrets
type: Opaque
stringData:
  DB_USER: {{ index .Values "rag-core" "secrets" "dbUser" | quote }}
  DB_PASSWORD: {{ index .Values "rag-core" "secrets" "dbPassword" | quote }}
  ENCRYPTION_KEY: {{ index .Values "rag-core" "secrets" "encryptionKey" | quote }}
  JWT_SECRET_KEY: {{ index .Values "rag-core" "secrets" "jwtSecretKey" | quote }}
  SERVICE_ACCOUNT_EMAIL: {{ index .Values "rag-core" "secrets" "serviceAccountEmail" | quote }}
  SERVICE_ACCOUNT_PASSWORD: {{ index .Values "rag-core" "secrets" "serviceAccountPassword" | quote }}
  S3_ACCESS_KEY_ID: {{ index .Values "rag-core" "secrets" "s3AccessKeyId" | quote }}
  S3_SECRET_ACCESS_KEY: {{ index .Values "rag-core" "secrets" "s3SecretAccessKey" | quote }}
  S3_BUCKET_NAME: {{ index .Values "rag-core" "secrets" "s3BucketName" | quote }}
  S3_ENDPOINT_URL: {{ index .Values "rag-core" "secrets" "s3EndpointUrl" | quote }}
  LLM_GATEWAY_URL: {{ index .Values "rag-core" "secrets" "llmGatewayUrl" | quote }}
  LANGCHAIN_API_KEY: {{ index .Values "rag-core" "secrets" "langchainApiKey" | quote }}