global:
  scrape_interval: "15s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "litellm-proxy"
    metrics_path: /metrics
    static_configs:
      - targets: ["litellm-proxy:8003"]
  
  - job_name: "rag-core-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["rag-core-api:8001"]