global:
  scrape_interval: "15s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "llm-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["llm-gateway:8002"]
  
  - job_name: "rag-core"
    metrics_path: /metrics
    static_configs:
      - targets: ["rag-core:8001"]

  - job_name: "postgres"
    metrics_path: /metrics
    static_configs:
      - targets: ["pg-exporter:9187"]
  
  - job_name: "rag-evaluation"
    metrics_path: /metrics
    static_configs:
      - targets: ["evaluation-runner:8004"]
